export const QUERY_KEYS = {
  me:             ["me"]                              as const,
  workMineList:   ["work", "mine", "list"]            as const,
  workMineDetail: (id: string)   => ["work", "mine", id]    as const,
  workDetail:     (slug: string) => ["work", slug]           as const,
  person:         (slug: string) => ["person", slug]         as const,
  personWork:     (slug: string) => ["person", slug, "work"] as const,
  peopleList:     (params?: object) => ["people", "list", params ?? {}] as const,
  workList:       (params?: object) => ["work", "list",   params ?? {}] as const,
  trafficSummary:      ["traffic", "summary"]       as const,
  moderationReports:   ["moderation", "reports"]    as const,
  moderationAppeals:   ["moderation", "appeals"]    as const,
  moderationLog:       ["moderation", "log"]        as const,
  moderationSettings:  ["moderation", "settings"]   as const,
}
