import { useEffect } from "react"
import { useNavigate } from "react-router-dom"
import { Container } from "@/components/layout/Container"
import { PageIntro, Prose, Section } from "@/components/layout/PageIntro"
import { Button } from "@/components/ui/Button"
import { ArrowRight } from "@/components/ui/Icon"
import { applyMeta } from "@/lib/head"

const RULES = [
  {
    rule: "Two published entries per topic, per person",
    why: "It forces people to lead with their best two, keeps a topic page readable, and makes density a feature rather than a race. Drafts are unlimited; unpublishing frees a slot.",
  },
  {
    rule: "Every entry states the problem, the decisions, and what changed",
    why: "\"It never shipped\" is a valid outcome, and the seeded directory includes cancelled projects and accepted regressions on purpose. A portfolio where everything succeeded is not credible.",
  },
  {
    rule: "Proof points are labelled \"Results claimed\"",
    why: "We cannot verify a number. Presenting claimed figures as verified facts would be the single most damaging thing this product could do.",
  },
  {
    rule: "Covers are generated by default",
    why: "So confidential work is not second-class, and so the grid does not become a visual-design competition among people who are not visual designers. Uploads are allowed and still carry the metric.",
  },
  {
    rule: "Simulated data says that it is simulated",
    why: "The traffic panel in this build is generated, and it tells you so. The one screen whose job is to be factual must not be the one that lies.",
  },
]

const NOT_BUILT = [
  ["Messaging, shortlists, job posts", "A two-sided hiring flow is a different product."],
  ["Likes, follows, feeds", "Popularity ranking reintroduces exactly the dynamic this exists to avoid."],
  ["Verification badges", "Attractive, and hard. Doing it badly is worse than not doing it."],
  ["AI-written case studies", "The form's whole value is that a person answered the questions."],
]

export function AboutPage() {
  const navigate = useNavigate()

  useEffect(() => {
    return applyMeta({
      title: "About",
      description: "Why a portfolio should be segmented by craft and evidenced by outcome, and the rules that make it hard to publish anything else.",
    })
  }, [])

  return (
    <div>
      <PageIntro
        eyebrow="About"
        title="The work, not the mockup"
        lede="A directory of people who build technology, and - the part that matters - the real work they have done. Not a picture of the work: the problem, the decisions, and the number that changed."
      />

      <Prose>
        <Section title="Why it exists">
          <p>
            Hiring evidence in tech barely exists in portable form. A CV compresses three years
            into six bullets and a job title that reflects one company's levelling. LinkedIn
            optimises for keywords, so everyone converges on the same vocabulary. Dribbble and
            Behance show what work <em>looked like</em> - a reviewer cannot tell whether it shipped
            or what changed. GitHub is real evidence for exactly one craft, and only for public
            code.
          </p>
          <p>
            A reviewer wants three facts in ten seconds: what was the problem, what did this person
            decide, what changed. Almost no portfolio surface makes those easy to state, so people
            write prose that hides them.
          </p>
        </Section>

        <Section title="The thesis">
          <p>
            A portfolio should be segmented by craft, evidenced by outcome, and the product should
            make it hard to publish anything else.
          </p>
          <p>
            Two consequences run through the whole build. <strong>The form is the product</strong> -
            what you ask determines what you get, so asking a developer for p95 and a repo, and a
            researcher for who they interviewed and what the team decided, produces better entries
            than one generic description box. And <strong>nobody wins on presentation</strong> - a
            prettier mockup must not out-rank a better result.
          </p>
        </Section>

        <Section title="Three axes, and why the third one is not an industry">
          <p>
            Work is filed by <strong>craft</strong> (what you do), <strong>topic</strong> (where it
            shipped) and <strong>business model</strong> (how the thing made money). Craft is set per
            entry rather than per person: a designer who shipped a routing engine files it as
            developer work, and the interface says so.
          </p>
          <p>
            Topic covers two different kinds of thing on purpose. An <em>industry</em> - banking,
            ERP, gaming - carries a business case almost by definition. A <em>practice</em> - design
            ops, hiring, reliability, accessibility - usually does not. That work is real and often
            the most senior thing a person has done, and filing it under an industry would either
            flatter it with a business case it never had or bury it entirely. The topic filter
            groups the two so they are never mistaken for each other.
          </p>
        </Section>

        <Section title="The rules that are the product">
          <dl className="flex flex-col gap-6">
            {RULES.map((item) => (
              <div key={item.rule} className="border-t border-line pt-4">
                <dt className="font-display text-base font-semibold text-ink">{item.rule}</dt>
                <dd className="mt-2 text-sm leading-relaxed text-muted">{item.why}</dd>
              </div>
            ))}
          </dl>
        </Section>

        <Section title="Deliberately not built">
          <dl className="flex flex-col gap-4">
            {NOT_BUILT.map(([what, why]) => (
              <div key={what}>
                <dt className="font-display text-sm font-semibold text-ink">{what}</dt>
                <dd className="mt-1 text-sm text-muted">{why}</dd>
              </div>
            ))}
          </dl>
        </Section>

        <Section title="What this build actually is">
          <p>
            A front-end demo. The people and case studies you are reading are seeded fixtures, and
            anything you create lives in your own browser's storage - nothing is uploaded and there
            is no account on any server. An API exists in the repository and is not yet wired to
            this interface.
          </p>
        </Section>
      </Prose>

      <Container className="pb-24">
        <div className="flex flex-col items-start gap-4 rounded-card border border-ink bg-ink p-7 text-paper sm:flex-row sm:items-center sm:justify-between">
          <p className="max-w-md text-sm leading-relaxed text-paper/80">
            The fastest way to understand the argument is to read two entries and notice what they
            are required to say.
          </p>
          <Button variant="pop" onClick={() => navigate("/work")}>
            Browse the portfolios
            <ArrowRight size={16} />
          </Button>
        </div>
      </Container>
    </div>
  )
}
